#!/bin/sh

### BEGIN INIT INFO
# Provides:          sniffer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sniffer Agent
# Description:       Sniffs traffic from/to sandboxes.
### END INIT INFO

mount_tmpfs="mount -t tmpfs -o size=20g tmpfs /var/caps"
unmount_tmpfs="umount /var/caps"

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/usr/share/MiddleRouter
DAEMON=$DIR/start_sniffer.py
DAEMON_NAME=sniffer

stdout_log="/var/log/$DAEMON_NAME.log"
stderr_log="/var/log/$DAEMON_NAME.err"

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    echo "Creating directory /var/caps where to store capture files"
    if [ ! -d "/var/caps" ]
    then
        mkdir "/var/caps"
    fi

    # We don't want to use any RAMDISK for now
    #$mount_tmpfs

    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --no-close --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS  >> "$stdout_log" 2>> "$stderr_log"
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --no-close --pidfile $PIDFILE --retry 10
    log_end_msg $?

    echo "Removing capture files"
    # $unmount_tmpfs
    if [ -d "/var/caps" ]
    then
        rm -R "/var/caps"
    fi
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
